[project]
name = "tender-soul-of-ocean-kkk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "flask-socketio>=5.5.1",
    "lap>=0.5.12",
    "noise>=1.2.2",
    "pyinstaller>=6.15.0",
    "pymodbus>=3.9.2",
    "pyserial>=3.5",
    "python-osc>=1.9.3",
    "pytubefix>=8.13.1",
    "scipy>=1.15.3",
    "stupidartnet>=1.6.0",
    "ultralytics>=8.3.139",
]
